### ISSUE TITLE
fastdfs-nginx-module_v1.05 does not compile with FastDFS_v3.00

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jerry-he/fastdfs#20]
```
What steps will reproduce the problem?
1. make and install FastDFS 3.00
2. configure nginx with fastdfs nginx module
3. failed to make nginx and fastdfs module

What is the expected output? What do you see instead?
make[1]:  `/home/u10/src/nginx-1.0.4'
gcc -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter 
-Wunused-function -Wunused-variable -Wunused-value -Werror -g  
-D_FILE_OFFSET_BITS=64 -DFDFS_OUTPUT_CHUNK_SIZE='256*1024' 
-DFDFS_MOD_CONF_FILENAME='"/etc/fdfs/mod_fastdfs.conf"'  -I src/core -I 
src/event -I src/event/modules -I src/os/unix -I /usr/local/include/fastdfs -I 
/usr/local/include/fastcommon/ -I objs -I src/http -I src/http/modules -I 
src/mail \
                -o objs/addon/src/ngx_http_fastdfs_module.o \
                /home/u10/src/fastdfs-nginx-module/src//ngx_http_fastdfs_module.c
In file included from 
/home/u10/src/fastdfs-nginx-module/src//ngx_http_fastdfs_module.c:6:
/home/u10/src/fastdfs-nginx-module/src//common.c: In function 
‘fdfs_http_request_handler’:
/home/u10/src/fastdfs-nginx-module/src//common.c:392: error: 
‘FDFS_FILE_PATH_LEN’ undeclared (first use in this function)
/home/u10/src/fastdfs-nginx-module/src//common.c:392: error: (Each undeclared 
identifier is reported only once
/home/u10/src/fastdfs-nginx-module/src//common.c:392: error: for each function 
it appears in.)


What version of the product are you using? On what operating system?


Please provide any additional information below.

```

Original issue reported on code.google.com by `yeb...@gmail.com` on 30 Jun 2011 at 2:30
